/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app-routing.module';
import * as i2 from './home/home.component.ngfactory';
import * as i3 from './platform/platform.component.ngfactory';
import * as i4 from './simulator/simulator.component.ngfactory';
import * as i5 from './showcase/showcase.component.ngfactory';
import * as i6 from './showcase/breath-monitor/breath-monitor.component.ngfactory';
import * as i7 from './explore/explore.component.ngfactory';
import * as i8 from './explore/recommended-reading/recommended-reading.component.ngfactory';
import * as i9 from './about/about.component.ngfactory';
import * as i10 from './terms/terms.component.ngfactory';
import * as i11 from '@angular/router';
import * as i12 from '@angular/common';
import * as i13 from '../../../src/app/home/home.component';
import * as i14 from '../../../src/app/platform/platform.component';
import * as i15 from '../../../src/app/simulator/simulator.component';
import * as i16 from '../../../src/app/showcase/showcase.component';
import * as i17 from '../../../src/app/showcase/breath-monitor/breath-monitor.component';
import * as i18 from '../../../src/app/explore/explore.component';
import * as i19 from '../../../src/app/explore/recommended-reading/recommended-reading.component';
import * as i20 from '../../../src/app/about/about.component';
import * as i21 from '../../../src/app/terms/terms.component';
export const AppRoutingModuleNgFactory:i0.NgModuleFactory<i1.AppRoutingModule> = i0.ɵcmf(i1.AppRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.HomeComponentNgFactory,i3.PlatformComponentNgFactory,i3.PlatformOverviewComponentNgFactory,
              i3.PlatformGettingStartedComponentNgFactory,i3.PlatformTechspecsComponentNgFactory,
              i3.PlatformDownloadsComponentNgFactory,i4.SimulatorComponentNgFactory,
              i4.SimulatorOverviewComponentNgFactory,i4.SimulatorGettingStartedComponentNgFactory,
              i4.SimulatorDocumentationComponentNgFactory,i4.SimulatorExamplesComponentNgFactory,
              i5.ShowcaseComponentNgFactory,i6.BreathMonitorComponentNgFactory,i7.ExploreComponentNgFactory,
              i8.RecommendedReadingComponentNgFactory,i9.AboutComponentNgFactory,i10.TermsComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i11.ActivatedRoute,
          i11.ɵf,[i11.Router]),i0.ɵmpd(4608,i11.NoPreloading,i11.NoPreloading,([] as any[])),
          i0.ɵmpd(6144,i11.PreloadingStrategy,(null as any),[i11.NoPreloading]),i0.ɵmpd(135680,
              i11.RouterPreloader,i11.RouterPreloader,[i11.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i11.PreloadingStrategy]),i0.ɵmpd(4608,i11.PreloadAllModules,
              i11.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i0.NgProbeToken,() => {
            return [i11.ɵb()];
          },([] as any[])),i0.ɵmpd(4608,i11.ɵg,i11.ɵg,[i0.Injector]),i0.ɵmpd(5120,
              i0.APP_INITIALIZER,(p0_0:any) => {
                return [i11.ɵh(p0_0)];
              },[i11.ɵg]),i0.ɵmpd(5120,i11.ROUTER_INITIALIZER,i11.ɵi,[i11.ɵg]),i0.ɵmpd(5120,
              i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
                return [p0_0];
              },[i11.ROUTER_INITIALIZER]),i0.ɵmpd(1024,i11.ɵa,i11.ɵd,[[3,i11.Router]]),
          i0.ɵmpd(512,i11.UrlSerializer,i11.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i11.ChildrenOutletContexts,i11.ChildrenOutletContexts,([] as any[])),
          i0.ɵmpd(256,i11.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i12.LocationStrategy,
              i11.ɵc,[i12.PlatformLocation,[2,i12.APP_BASE_HREF],i11.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i12.Location,i12.Location,[i12.LocationStrategy]),i0.ɵmpd(512,
              i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i11.ROUTES,() => {
            return [[{path:'',redirectTo:'/home',pathMatch:'full'},{path:'home',component:i13.HomeComponent},
                {path:'platform',component:i14.PlatformComponent,children:[{path:'',
                    redirectTo:'overview',pathMatch:'full'},{path:'overview',component:i14.PlatformOverviewComponent},
                    {path:'getting-started',component:i14.PlatformGettingStartedComponent},
                    {path:'techspecs',component:i14.PlatformTechspecsComponent},{path:'downloads',
                        component:i14.PlatformDownloadsComponent}]},{path:'simulator',
                    component:i15.SimulatorComponent,children:[{path:'',redirectTo:'overview',
                        pathMatch:'full'},{path:'overview',component:i15.SimulatorOverviewComponent},
                        {path:'getting-started',component:i15.SimulatorGettingStartedComponent},
                        {path:'documentation',component:i15.SimulatorDocumentationComponent},
                        {path:'examples',component:i15.SimulatorExamplesComponent}]},
                {path:'showcase',component:i16.ShowcaseComponent},{path:'showcase/breath-monitor',
                    component:i17.BreathMonitorComponent},{path:'explore',component:i18.ExploreComponent},
                {path:'explore/recommended-reading',component:i19.RecommendedReadingComponent},
                {path:'about',component:i20.AboutComponent},{path:'terms-and-conditions',
                    component:i21.TermsComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i11.Router,i11.ɵe,[i0.ApplicationRef,i11.UrlSerializer,
              i11.ChildrenOutletContexts,i12.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i11.ROUTES,i11.ROUTER_CONFIGURATION,[2,i11.UrlHandlingStrategy],
              [2,i11.RouteReuseStrategy]]),i0.ɵmpd(512,i11.RouterModule,i11.RouterModule,
              [[2,i11.ɵa],[2,i11.Router]]),i0.ɵmpd(512,i1.AppRoutingModule,i1.AppRoutingModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvc3VmYW5nL09uZURyaXZlL05WTGFicy9zcmMvYXBwL2FwcC1yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9zdWZhbmcvT25lRHJpdmUvTlZMYWJzL3NyYy9hcHAvYXBwLXJvdXRpbmcubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
